<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Breadcrumb Languages
	|--------------------------------------------------------------------------
	*/
	"home" 						=> "Home",
	"members_list" 				=> "Members List",
	"add_user" 					=> "Add User",
	"edit_user" 				=> "Edit User",
	"payment_list" 				=> "Payment Listing",
	'add_payment'         	 	=> 'Submit Payment Details',
	'edit_payment'       		=> 'Update Payment Details',
	'withdrawal_list'       	=> 'Withdrawal List',
	'transaction_list'       	=> 'Transactions',
	'add_transaction'       	=> 'Debit Money',
	'gateway_list'       		=> 'Payment Types',
	'add_gateway'       		=> 'Add Payment Type',
	'edit_gateway'       		=> 'Edit Payment Type',
	'account_list'       		=> 'Payment Accounts',
	'add_account'       		=> 'Add Account',
	'edit_account'       		=> 'Edit Account',
	'config_manage'       		=> 'Config Management',
	'groups_list'       		=> 'Manage Groups',
	'groups_members_list'       => 'Group Members',
	'groups_access_list'       	=> 'Manage Access',
	'edit_groups_access'       	=> 'Edit group access',
	'view_enquiry'       		=> 'View Enquiry',
	'messages_list'       		=> 'Messages List',
	'view_enquiry'       		=> 'View Message',
	'manage_member_access'      => 'Manage member access',
	'manage-unlock-tools'       => 'Manage Unlock Tools',
	'reply-accepted-order'      => 'Reply Accepted Order',
	'login_history'				=> 'Login History',
	'order_history'				=> 'Order History',
	'order_history_all'			=> 'Show All Order History',
	'order_history_new'			=> 'New Order History',
	'order_history_accepted'	=> 'Accepted Order History',
	'order_history_rejected'	=> 'Rejected Order History',
	'order_history_cancelled'	=> 'Cancelled Order History',
	'order_history_service_wise'	=> 'Service Wise Order History',
	'order_history_quick_accept'	=> 'Quick Accept Imei Orders',
	'order_history_quick_accept_process_order'	=> 'Quick Accept Process Orders',

	'file_order_history'				=> 'Order History',
	'file_order_history_all'			=> 'Show All Order History',
	'file_order_history_new'			=> 'New Order History',
	'file_order_history_accepted'		=> 'Accepted Order History',
	'file_order_history_rejected'		=> 'Rejected Order History',
	'file_order_history_cancelled'		=> 'Cancelled Order History',
	'file_order_history_service_wise'	=> 'Service Wise Order History',
	'file_order_history_quick_accept'	=> 'Quick Accept File Orders',
	'file_order_history_quick_accept_process_order'	=> 'Quick Accept Process Orders',
	'imei_service_orders'				=>  'IMEI Service Orders',
	'file_service_orders'				=>  'File Service Orders',


	'manage_jobs'				=> 'Manage Jobs',
	'api_service'				=> 'Api Service List',
	'add_credit'				=> 'Add Credit',
	'list_transaction'			=> 'Transaction List',
	'api_service_edit'			=> 'Api Service Edit',
	'mass_email'				=> 'Mass Email',
	'mass_email_compose'		=> 'Mass Email Compose',
	'mass_email_list'			=> 'Mass Email List',
	'mass_email_edit'			=> 'Edit',
	'mass_email_view'			=> 'View',
	'api_service_groups'		=> 'Add Service Group',
	'list_api_service_groups'	=> 'List Service Group',
	'edit_api_service_groups'	=> 'Edit Service Group',
	'imei_service'				=> 'IMEI Service',
	'imei_service_add'			=> 'Add New Service',
	'imei_service_list'			=> 'List All IMEI Services',
	'imei_service_edit'			=> 'Edit  IMEI Services',
	'api_server_setting_list'	=> 'Api Server Setting List',
	'api_server_setting'		=> 'Api Server Setting',
	'api_server_setting_edit'	=> 'Edit',
	'api_server_service_list'	=> 'Service List',
	'imei_service_quick_edit'	=> 'Quick Edit',
	'file_service_groups'		=> 'Add File Service Group',
	'list_file_service_groups'	=> 'List File Service Group',
	'edit_file_service_groups'	=> 'Edit File Service Group',
	'file_service'				=> 'File Service',
	'file_service_add'			=> 'Add New File Service',
	'file_service_list'			=> 'List All File Services',
	'file_service_edit'			=> 'Edit  File Services',
	'add_supplier'				=>	'Add Supplier',
	'manage_supplier'			=>	'Suppliers List',
	'api_log_list'				=>	'API Log',
	'client_group'				=>	'Client Group',
	'overview'					=>  'Overview',
	'account'					=>  'Account',
	'edit_profile'				=>  'Edit Profile',
	'allow_imei_service'		=>  'Allow IMEI Service',
	'allow_file_service'		=>  'Allow File Service',
	'allow_server_service'		=>  'Allow Server Service',
	'file_service_quick_edit'	=> 'Quick Edit',

	'reseller_site_settings_list' => 'Reseller Site Settings List',
	'reseller_site_settings_add' => 'Add Reseller Site Settings',
	'reseller_site_settings_edit' => 'Edit  Reseller Site Settings',

	'cms_menu_manager' 				=> 'Menu Manager',
	'cms_page_content_index' 		=> 'Page Content Index',
	'cms_page_content_contactus' 	=> 'Page Content Contact Us',
	'cms_custom_page' 				=> 'Custom Page',
	'cms_banner_settings' 			=> 'Banner Settings',

	'chat_history' 					=> 'Chat History',
	'view_history' 					=> 'View Chat History',
	'list_banned_ip' 				=> 'Chat Banned IP List',
	'list_chat_group' 				=> 'Chat Group List',
	'list_chat_group_members' 		=> 'Chat Group Members',
	'list_shortcut' 				=> 'Chat Shortcut List',
	'manage_shortcut' 				=> 'Manage Chat Shortcut',
	'transfer_credit' 				=> 'Transfer Credit',
	'add_blocked_ip' 				=> 'Add Blocked IP',
	'add_whitelisted_ip' 			=> 'Add Whitelisted IP',

	'server_service_groups'		    => 'Add Service Group',
	'list_server_service_groups'	=> 'List Service Group',
	'edit_server_service_groups'	=> 'Edit Service Group',
	'server_service'				=> 'Server Service',
	'server_service_group'			=> 'Server Service Group',
	'server_service_add'			=> 'Add New Service',
	'server_service_list'			=> 'List All Server Services',
	'server_service_edit'			=> 'Edit  Server Services',
	'server_service_quick_edit'		=> 'Quick Edit',

	'field_setting'					=> 'Field Settings',
	'field_setting_country'			=> 'Add Country',
	'field_setting_country_list'	=> 'Country List',
	'field_setting_country_edit'	=> 'Edit Country',
	'field_setting_provider'		=> 'Add Provider',
	'field_setting_provider_list'	=> 'Provider List',
	'field_setting_provider_edit'	=> 'Provider Edit',
	'field_setting_brand'			=> 'Add Brand',
	'field_setting_brand_list'		=> 'Brand List',
	'field_setting_brand_edit'		=> 'Brand Edit',
	'field_setting_model'			=> 'Add Model',
	'field_setting_model_list'		=> 'Model List',
	'field_setting_model_edit'		=> 'Model Edit',
	'field_setting_mep'				=> 'Add Mep',
	'field_setting_mep_list'		=> 'Mep List',
	'field_setting_mep_edit'		=> 'Mep Edit',


	'knowledge'						=> 'Add Knowledge Base',
	'knowledge_edit'				=> 'Knowldge Base Edit',
	'knowledge_list'				=> 'Knowledge Base List',
	'knowledge_category'			=> 'Knokekdge Base Country',
	'knowledge_category_edit'		=> 'Knowledge Base Category Edit',
	'knowledge_category_list'		=> 'Knowledge Base Category List',

	'admin_dashboard'				=> 'DashBoard',

	'ticket_setting'				=> 'Ticket Service Settings',
	'ticket_view'					=> 'View Ticket',
	'ticket_list'					=> 'List Ticket',

	'download_category'				=> 'Category',
	'download_category_list'		=> 'Category List',
	'download_category_edit'		=> 'Edit Category',
	'download_download'				=> 'Download',
	'download_download_list'		=> 'Download List',
	'download_download_edit'		=> 'Edit Download',

	'system_summary'				=> 'System Summary',
	'online_users'					=> 'Online Users',
	'download_log'					=> 'Download Logs',
	'gateway_log'					=> 'Gateway Log',
	'top_users_by_income'			=> 'Top Users By Income',

	'sales_by_product_imei'			=> 'Sales By Product IMEI',
	'sales_by_product_file'			=> 'Sales By Product File',
	'sales_by_product_server'		=> 'Sales By Product Server',

	'monthly_order_imei'			=> 'Monthly Orders IMEI',
	'monthly_order_file'			=> 'Monthly Orders File',
	'monthly_order_server'			=> 'Monthly Orders Server',

	'service_status'                => 'Service Status',
	'service_status_imei'			=> 'IMEI',
	'service_status_server'			=> 'Server',

	'refund_report'                 => 'Refund Report',
	'refund_report_imei'			=> 'IMEI',
	'refund_report_file'			=> 'File',
	'refund_report_server'			=> 'Server',

	'supplier_order'                => 'Supplier Order',
	'supplier_order_report_imei'	=> 'IMEI',
	'supplier_order_report_file'	=> 'File',
	'supplier_order_report_server'	=> 'Server',

	'admin_credit_report'			=> 'Credit Report',
	'reports'						=> 'Reports/Graphs',

	'graph_user_account_status'		=> 'Account Status',
	'graph_monthly_income'			=> 'Monthly Income',
	'graph_monthly_order'			=> 'Montly Order',
	'graph_monthly_signup'			=> 'Monthly Signup',

	'template_manage'      			=> 'Template Management',
	'payment-block-list'            => 'Payment Block List',
	'maintenance-mode'              => 'Maintenance Mode',
	'site-logo-settings'            => 'Site Logo Settings',
	
	'admin-list'                    => 'Admin List',
	'admin-role'                    => 'Aministrator Role',
	
	'customer-reply'                => 'Customer Reply',
	'answered-tickets'              => 'Answered Tickets',
	'closed-tickets'                => 'Closed Ticketets',
	'opened-tickets'                => 'Open Tickets',
	'waiting-tickets'               => 'Waiting Tickets', 
	'newsletter-subscriber'         => 'News Letter Subscriber',
	
	'invoice-reports'               => 'Invoice Reports',
	
	'paypal-transaction'            => 'Paypal Transactions',
	
	'reseller_orders_imei'          => 'Order Summary IMEI',
	'reseller_orders_file'          => 'Order Summary File',
	'reseller_orders_server'        => 'Order Summary Server',
	'imei-service-group'            => 'IMEI Service Group',
	'imei-service'                  => 'IMEI Service',
	'imei-add-service'              => 'Add New Service',
	'file-add-service'              => 'Add New Service',
	'server-add-service'            => 'Add New Service',
	
	'api-log'                       => 'API Log',
	'newsletter-subscriber'         => 'NewsLetter Subscriber',
	
	'database'                      => 'Database Backup',
	'database-backup-option'        => 'Option',
	'database-backup-list'          => 'List',
	'database-backup-status'        => 'Status',
	
	'mass-email-list'               => 'Mass Email',
	
	'gateway-settings'              => 'Gateway Settings',
	'api-settings'                  => 'API Settings',
	'self-update'                   => 'Search New Version',
	
	'order-history-quick-accept'    => 'Quick Accept Order',
	'order-history-service-wise'    => 'Service Wise Order',
	'order-list-verification-order' => 'Orders for Verification',
	'order-list-verification'       => 'Orders For Verification',
	
	'invoice'         				=> 'Invoice',
	'unpaid-invoice'         		=> 'Invoice',
	'unpaid-invoice-byuser'         => 'By User',
	'unpaid-invoice-byAdmin'        => 'By Admin',
	'unpaid-invoice-byall'          => 'By All',
	
	'supplier_dashboard'            => 'Dashboard',
	'imei_orders_service_wise'      => 'Service Wise IMEI Order',
	'imei_orders_Quick_accept'      => 'Quick Accept IMEI Order',
	'imei_orders_verification'      => 'Orders For Verification',
	'imei_orders_history'           => 'Order History',
	'reply_acdepted_orders'         => 'Reply Accept Order',
	'file_orders_service_wise'      => 'Service Wise File Order',
	'file_orders_Quick_accept'      => 'Quick Accept File Order',
	'file_order_verification'       => 'Orders For Verification',
	'file_orders_history'           => 'Order History',
	'server_orders_service_wise'    => 'Service Wise Server Order',
	'server_orders_Quick_accept'    => 'Quick Accept Server Order',
	'server_orders_verification'    => 'Orders For Verification',
	'server_orders_history'         => 'Order History',
	'supplier_edit_profile'         => 'My Profile',
	'supplier_statement'            => 'Statement List',
	'supplier_order_transaction'    => 'Order Transaction',
	'supplier_reply_accepted_order' => 'Reply Accepted Order',
	
	'manage_language_settings'      => 'Language Settings',
	'manage_language_edit'          => 'Edit Languages',
	'manage_language_export'        => 'Export Languages',
	'manage_language_import'        => 'Import Languages',
	'manage_language_list'          => 'Languages List',
	
	'cdr_manage'      				=> 'CDR Management',
);
