<?php

return array(
	"userActivation" => "Your  account confirmation",
	"Visitor_Name" => "Visitor Name",
	"Visitor_Email" => "Visitor Email",
	"page_title" => "Live Chat",
	'livechat' => 'Live Chat',
	"subject" => "Subject",
	"name" => "Your Name",
	"email" => "Email Address",
	"mobile_no" => "Phone Number",
	"comments" => "Message",
	"support_submit" => "Submit",
	"subject_empty_err_msg" => "Please enter subject",
	"name_empty_err_msg" => "Please enter your name",
	"email_empty_err_msg" => "Please enter email",
	"mobile_empty_err_msg" => "Please enter mobile number",
	"comments_empty_err_msg" => "Please enter your description",
	"chat_username_label" => "Name",
	"chat_question_label" => "Question",
	"chat_email_label" => "Email",
	"chat_email_subject_label" => "Subject",
	"chat_submit" => "Submit",
	"chat_email_message_label" => "Message",
	"chat_err_tip_compulsory" => "Required",
	"chat_captcha" => "Captcha",
	"chat_visitor_request_msg" => "User VAR_VISITOR_USER_NAME wants to chat with you",
	"supporter_offline_msg" => "Your live sales operator went offline due to a technical problem, do you want to submit your request instead?",
	"supporter_req_submitted_msg" => "Your message has been sent. One of our sales staff will get back to you shortly.",
	"visitor_offline_msg_to_supporter" => "Visitor VAR_VISITOR_USER_NAME went offline.",
	"no_supporters_available" => "There are no live sales operators online. Your message has been sent. One of our sales staff will get back to you shortly.",
	"unassigned_supporters" => "User VAR_VISITOR_USER_NAME is now chatting with VAR_SUPPORTER_NAME.",
	"start_to_connect_supporter" => "All our live sales operators are currently busy, please wait and an operator will be with you shortly.",
	"connecting_supporters" => "Your request is important to us. Please wait while we connect you with an available live sales operator.",

	"help_tip_msg"  => " Enter \\\help to get the list of predefined commands.",
	"invalid_shortcut_msg"  => "Command not recognized. Use \\\help for more information about available commands.",
	"msg_undelivered_alert" => "Your message could not be delivered. Please wait for an operator to accept your request.",
	"unauthorized_msg_alert" => "Your message could not be delivered. Your connection is closed.",
	"assigned_supporter_msg" => "You are now chatting with VAR_SUPPORTER_NAME",
	"success_mail" => "There are no live sales operators online. Your message has been sent. One of our sales staff will get back to you shortly.",
	"failed_mail" => "Unfortunately a technical problem prevented you mail from being sent, please try again",
	"jabber_server_down" => "Unfortunately a technical problem is preventing us from connecting to the chat server, please try again",
	"not_allowed_to_chat_msg" => "Sorry, you do not have a chat in progress with this user",
	"transfer_connection" => "Transferring support request to VAR_TRANSFER_NAME",
	"banned_ip_alert_msg" => "Your IP is blocked due to invalid request data.",
	"banned_ip_success_msg" => "Visitor IP has been Banned!",
	"banned_ip_failed_msg" => "Visitor IP has not been Banned!",
	"transfer_connection_request_decline" => "VAR_TRANSFER_NAME declined your transfer request",
	"transferred_supporter_msg" => "You are now in charge of this chat (type \\\help for commands).",
	"invalid_transferred_msg" => "Command not recognized. Use \\\help for more information about available commands.",
	"invalid_transfer_req_msg" => "Invalid transfer request.",
	"invalid_visitor_name_msg" => "Enter only alphabets.",
	"status_online" => "Online",
	"status_offline" => "Offline",
	"msg_undelivered" => "Undelivered",
	"email_subject" => "VAR_SITE_NAME: Offline contact message from VAR_VISITOR_NAME",
	"banned_ip_errmsg" => "Sorry this IP has been banned. If you want submit any request please write to us at VAR_EMAIL_BANNED_IP.",
	"visitor_chat_history_subject" => "VAR_SITE_NAME: Chat history",
	"prompt_chat_history_msg" => "Do you want to send chat history to your email?.",
	"chat_history_sent_msg" => "Chat history sent to your email address!!!.",
	"live_chat_btn" => "Live Chat",
	"leave_mail_btn" => "Leave us a message",
	"supporter_non_avail_msg" => "No sales operators online.",
	"chat_history_mail_tooltip_msg" => "Chat log will be sent to your mail at the end of the session",
	"send_mail_lbl" => "Send Mail",
	"send_chat_history_confirm_msg" => "Connection closed. Please CLICK_HERE to send the chat history to your mail.",
	"close_chat_window_msg" => "CLICK_HERE",
	"support_operator_lbl" => "Support operator",
	"supporteronline_status" => "Live Status: <span class='label label-success'>Online</span>",
	"supporteronline_notemsg" => "Click the 'Live Chat' button below to connect instantly and start chatting with a live support agent. Enter your email address to receive a copy of your conversation.",
	"supporteroffline_status" => "Live Status: <span class='label label-danger'>Offline</span>",
	"supporteroffline_notemsg" => "Support agents are currently offline. Submit a message below and we will promptly reply by email.",

	"optional" => "Optional",
	"no_history_found" => "No Chat History Found",
	"chat_history_lbl" => "Chat History",
	"visitor_name_lbl" => "Visitor name",
	"visitor_email_lbl" => "Visitor email",
	"visitor_ip_lbl" 	=> "Visitor IP",
	"date_chatted" 		=> "Chatted Date",
	"chat_history" 		=> "Chat History",
	"view_chat_history_title" 		=> "View Chat History",
	"my_chat_history" 		=> "My Chat History",	
	"visitor" 				=> "Visitor",
	"subject" 				=> "Subject",
	"chatted_on" 				=> "Chatted On",
	"chat_type" 				=> "Chat Type",
	"action_lbl" 				=> "Action",
	"chat_group" 				=> "Department",
	
	"Search_History" => 'Search History',
	'Chat_Histor_Management' => 'Chat History Management',
	'Visitor_Name' => 'Visitor Name',
	"Chatted_With" => "Chatted With",
	"Chat_Request" => "Chat Request",
	"Visitor_Email" => "Visitor Email",
	'Chat_History_List' => 'Chat History List',
	'ID' => 'ID',
	'Email' => 'Email',
	'IP' => 'IP', 
	'Supporter_Name' => 'Supporter Name',
	'Subject' => 'Subject',
	'Chatted_On' => 'Chatted On',
	
	'Add_banned_IP' => ' Add banned IP',
	'Banned_IP' => 'Banned IP',
	'Search_banned_IP' => 'Search banned IP',
	
	
	'Add_banned_IP' => ' Add banned IP',
	'Add_Group' => 'Add Group',
	"Group_Name" => "Group Name",
	"Search_Group" => "Search Group",
	'Chat_Group' => 'Chat Group',
	'Actions' => 'Actions',

);