<?php


return array(
	/*
	|--------------------------------------------------------------------------
	| invoice
	|--------------------------------------------------------------------------
	*/

	'unpaid_title'						=> 'Unpaid Invoice',
	'Search_Invoices'				=> 'Search Invoices',
	'User'				=> 'User',
	'Invoice_From'		=> 'Invoice From',
	'Date_Added'					=> 'Date Added',
	'Currency'	=> 'Currency',
	'Search_Type'				=> 'Search Type',
	'Name/Email'		=> 'Name / Email',
	'Invoice_List'		=> 'Invoice List',
	'generated_by'		=> 'Generated By',
	'assigned_to_staff_id'		=> 'Assigned To',


	'User_Name'	=> 'User Name',
	'Created_Date'	=> 'Created Date',
	'Due_Date'	=> 'Due Date',
	'date_paid'	=> 'Date Paid',
	'Flag'	=> 'Flag',
	'Total_Amount'	=> 'Total Amount',
	'Status'	=> 'Status',
	'Action'	=> 'Action',
	'date_added_from' => 'Date Added',
	'Currency' => 'Currency',	 
);