<?php

//@added by ravikumar_131at10

return array(
	/*
	|--------------------------------------------------------------------------
	| Payment
	|--------------------------------------------------------------------------
	*/

	'title'						=> 'Credits',
	'rejected_lbl'				=> 'Rejected',
	'completed_lbl'				=> 'Completed',
	'waiting_action_lbl'		=> 'Waiting Action (resubmit)',
	'new_lbl'					=> 'New',
	'waiting_action_insufficient_lbl'	=> 'Waiting Action (User Insufficient Balance)',
	'submitted_lbl'				=> 'Submitted (In Process)',
	'submitted_lbl_member'		=> 'Submitted',
	'add_credit'					=>array(
	'title'						=> 'Add Credit',
	'for_user'    				=> 'For User',
	'for_user_view'    			=> 'Credit to be added',
	'credit_amount' 			=> 'Credit Amount',
	'credit_note'  				=> 'Credit Note',
	'credit_note_placeholder'	=> 'Provide details on the credit for. Limit to 500 characters.',
	),
	'order_history'			=> array(
		'title'					=> 'Order History',
		'srch_order' 			=> 'Search Order',
		'order_code' 			=> 'Order Code',
		'model_name' 			=> 'Model',
		'status_label' 			=> 'Status',
		'api_status_label' 		=> 'Order Status',
		'unlock_code' 			=> 'Unlock Code',
		'imei_label' 			=> 'IMEI',
		'unlock_tool' 			=> 'Unlock Tool',
		'tool_name' 			=> 'Tool',
		'service_name' 			=> 'Service',
		'id' 					=> 'Id',
		'date_added' 			=> 'Date Added',
		'server_name'			=> 'Service',
		'username' 				=> 'Username',
		'no_records_found' 		=> 'No records found',
	),
	'list-transactions' => array(
		'title' 					=> 'Transaction History List',
		'page_title' 				=> 'Admin - transaction history',
		'transactions' 				=> 'Transactions',
		'srch_txn_history' 			=> 'Search Transaction History',
		'user' 						=> 'User',
		'transaction_type' 			=> 'Transaction Type',
		'currency' 					=> 'Currency',
		'date_added' 				=> 'Date Added',
		'to' 						=> 'To',
		'transaction_key' 			=> 'Transaction Key',
		'description' 				=> 'Description',
		'order_code' 				=> 'Order Code',
		'id' 						=> 'ID',
		'user_details' 				=> 'User Details',
		'date' 						=> 'Date',
		'type' 						=> 'Type',
		'amount' 					=> 'Amount',
		'balance' 					=> 'Balance',
		'transaction_notes' 		=> 'Transaction Notes',
		'no_txn_history_err_msg' 	=> 'No transaction history found to list',
		'transaction_type_credit' 	=> 'Credit',
		'transaction_type_debit' 	=> 'Debit',
		'imei_order_id' 			=> 'Order ID',
		'imei_label' 				=> 'IMEI',
		'service_label' 			=> 'Service',
		'view_log' 					=> 'View Log',
		'user_notes' 				=> 'User Notes',
		'admin_notes' 				=> 'Admin Notes',
		'view_order' 				=> 'View Order',
		'payment_method' 			=> 'Payment Method',
		'staff_transaction' 		=> 'Staff Transaction',
 	),
	'view-invoice' => array(
		'title'							=> 'Invoice Details',
		'summary'						=> 'Summary',
		'client'						=> 'Client',
		'invoice_date'					=> 'Invoice Date',
		'due_date'						=> 'Due Date',
		'total_due'						=> 'Total Due',
		'pending_due'					=> 'Pending',
		'invoice_items'					=> 'Invoice Items',
		'item'							=> 'Item',
		'amount'						=> 'Amount',
		'taxed'							=> 'Taxed',
		'invoice_sub_total'				=> 'Invoice Sub Total',
		'service_tax'					=> 'Service Tax',
		'fees'							=> 'Fees',
		'invoice_amount'				=> 'Invoice Amount',
		'invalid_invoice_id_err'		=> 'Invalid invoice id',
		'invoice_updated_succ_msg'		=> 'Invoice details updated successfully',
		'invoice_item_none_err'			=> 'No items found',
		'view_invoice_log'				=> 'View Invoice Log',
		'transaction_id'				=> 'Transaction Id',
		'payment_gateway_receiver'		=> 'Receiver',
		'set_paid_confirm_msg'			=> 'Are you sure to set this invoice as paid ?',
		'cancel_invoice_confirm_msg'	=> 'Are you sure to cancel this invoice ?',
		'mass_pay_user_info_msg'		=> 'Mention your email address in "Email subject" field when you proceed with mass payment in order to process your transaction faster.',
		'gift_pay_user_info_msg'		=> 'Mention your email address in "Email subject" field when you proceed with gift payment in order to process your transaction faster.',
		'by_cash_user_info_msg'			=> 'Pay to admin, once admin received the amount invoice will be set as paid.',
	),
	'list-pending-transaction' => array(
		'transactionid'					=> 'Transaction Id',
		'sender_email'					=> 'Sender Email',
		'receiver_email'				=> 'Receiver Email',
		'payment_status'				=> 'Payment Status',
		'change_status_success'			=> 'Transaction status changed successfully',
		'admin_pending_transaction'		=> 'Paypal Transaction',
		'transaction_process_success'	=> 'Transaction processed successfully',
		'amount'						=> 'Amount',
		'email'							=> 'Email',
		'date_paid'						=> 'Date Paid',
		'transaction_process_error'		=> 'Sorry errors found! There seems an problem in processing the transaction',
		'transaction_accounts_status' 	=> array(
			 'pending'	=> 'Pending',
			 'already_exist' => 'Already Exist',
			 'added' => 'Added',
			 'ignore' => 'Ignored',
		),
		'status'			=> 'Status',
	),
	'transaction' => array(
		'page_title'	=>	'Check Paypal Transaction',
		'email'	=>	'Email',
		'api_user_name' => 'Api User Name',
		'action' => 'Action',
		'transaction_id' => 'Transaction Id',
		'receiver_email' => 'Receiver Email',
		'receiver_details' => 'Receiver Details',
		'add_api_details' => 'Add Api Details',
		'delete' => 'Delete',
		'edit' => 'Edit',
		'deleted_successfully' => 'Deleted Successfully',
		'added_successfully' => 'Added Successfully',
		'api_password' => 'Api Password',
		'api_signature' => 'Api Signature',
		'back_to_list' => 'Back to list',
		'edit_page_title' => 'Edit Api Details',
		'updated_successfully' => 'Updated Successfully',
		'invoice_id' => 'Invoice Id',
		'status' => 'Status',
		'user' => 'User',
		'amount' => 'Amount',
		'matching_invoice_details' => 'Matching Invoice Details',
		'search_results' => 'Search Results For Transaction Id :',
		'invoice_details' => 'Invoice Details',
		'receiver_business' => 'Receiver Business',
		'receiver_id' => 'Receiver Id',
		'payer_id' => 'Payer Id',
		'payer_status' => 'Payer Status',
		'country_code' => 'Country Code',
		'business' => 'Business',
		'address_owner' => 'Address Owner',
		'address_status' => 'Address Status',
		'subject' => 'Subject',
		'correlation_id' => 'Correlation Id',
		'version' => 'Version',
		'ack' => 'Ack',
		'build' => 'Build',
		'first_name' => 'First Name',
		'last_name' => 'Last Name',
		'transaction_type' => 'Transaction Type',
		'payment_type' => 'Payment Type',
		'order_time' => 'Order Time',
		'amt' => 'Amount',
		'currency_code' => 'Currency Code',
		'payment_status' => 'Payment Status',
		'pending_reason' => 'Pending Reason',
		'reason_code' => 'Reason Code',
		'protection_eligibility' => 'Protection Eligibility',
		'l_currency_code' => 'LCurrencyCode0',
		'l_taxable_0' => 'LTaxable0',
		'error' => 'Error'
	),
	'list-staff-balance' => array(
		'title' 					=> 'Staff Statement',		
		'user' 						=> 'User',
		'transaction_type' 			=> 'Transaction Type',		
		'date_added' 				=> 'Date Added',
		'to' 						=> 'To',		
		'id' 						=> 'ID',
		'user_details' 				=> 'User Details',
		'date' 						=> 'Date',
		'type' 						=> 'Type',
		'amount' 					=> 'Amount',
		'balance' 					=> 'Balance',
		'no_staff_txn_err_msg' 		=> 'No staff transaction found to list',
		'transaction_type_credit' 	=> 'Credit',
		'transaction_type_debit' 	=> 'Debit',
		'invoice_id' 				=> 'Invoice ID',		
		'staff_balance_title' 		=> 'Admin - Payment - Staff Balance',
		'staff_transaction_title' 	=> 'Admin - Payment - Staff Transaction',
		'staff_statement_title' 	=> 'Admin - Payment - Staff Statement',
		'transaction_id' 			=> 'Transaction ID',
		'notes' 					=> 'Notes',
		'search_staff_balance'		=> 'Search Staff Balance',
		'search_staff_transaction'	=> 'Search Staff Transaction',
		'search_staff_statement'	=> 'Search Staff Statement',
		'staff_balance_list'		=> 'Staff Balance List',
		'staff_transaction_list'	=> 'Staff Transaction List',
		'staff_statement_list'		=> 'Staff Statement List',
 	),
);