<?php
/**
 *
 *
 */

return array(
	'account_menu_my_transactions'		=> 'My Transactions',


	'account_menu_view_request'	=> 'View Request',
	'account_menu_edit_profile'	=> 'Edit Profile',
	'account_menu_clinet_area_dashboard'	=> 'Client Area Dashboard',
	'dashboard_Credit_Details'	=> 'Credit Details',
	'dashboard_avi_balance'	=> 'Available Balance',
	'dashboard_pending_order_balance'	=> 'Pending Orders Balance',
	'USD'				=> 'USD',
	'Available'				=> 'Available',
	'Rejected'				=> 'Rejected',
	'Pending'				=> 'Pending',

	'Last_20_IMEI_Orders'				=> 'Last 20 IMEI Orders',
	'All_Services'				=> 'All Services',
	'Pending'				=> 'Pending',
	'Pending'				=> 'Pending',
	'Pending'				=> 'Pending',

	'Pending'				=> 'Pending',
	'dashboard_completed_orders'	=>	'Completed Orders',








	'dashboard_tot_receipt_amount'	=> 'Total Receipt Amount',
	'dashboard_overdraft_limit'	=> 'Overdraft Limit',
	'dashboard_overdraft_availed'	=> 'Overdraft Availed',
	'dashboard_overdraft_available'	=> 'Overdraft Left',
	'dashboard_pending_order_overdraft'	=> 'Pending Overdraft',
	'account_menu_my_account'	=> 'My Account',
	'account_menu_notification'	=> 'Notification',
	'account_menu_my_request'	=> 'My Requests',
	'account_menu_my_transactions'		=> 'My Transactions',
	'account_menu_my_invoices'			=> 'My Invoices',
	'account_menu_account_balance'		=> 'Account Balance',
	'account_menu_withdrawal'		=> 'Withdrawal',
	'account_menu_settings'		=> 'Settings',
	'messages_label'			=> 'Messages',
	'account_menu_update_username'	=> 'Update Username',


	'edit-profile' => array(
		'new_email_activate_sucess' => 'Email address updated successfully. Please login below',
		'wrong_password' => 'Incorrect password',
		'basic_details_update_sucess' => 'Basic details updated successfully',
		'personal_details_update_sucess' => 'Personal details updated successfully',
		'company_details_update_sucess' => 'Company details updated successfully',
		'basic_details_title' => 'Basic Details',
		'current_email' => 'Current Email',
		'user_name' => 'Username',
		'new_email' => 'New Email',
		'current_password' => 'Current Password',
		'password' => 'New Password',
		'confirm_password' => 'Confirm Password',
		'personal_details_title' => 'Personal Details',
		'first_name' => 'First name',
		'last_name' => 'Last name',
		'contact_number' => 'Contact number',
		'city_state_country' => 'City, State, Country',
		'about_me' => 'About me',
		'Invalid_Credit_Amount' => 'Invalid Credit Amount',
		'your_photo' => 'Your Photo',
		'changepassword_success_message' => 'Your password has been changed.',
		'alternateEmail_newEmail_activation_msg' => 'Please click the confirmation link sent to your email address to confirm the email change.',
		'edit_profile' => 'Edit Profile',
		'billing_details_title' => 'Billing Details',
		'billing_name' => 'Name',
		'company_name' => 'Company',
		'address_title' => 'Address',
		'city_name' => 'City',
		'state_name' => 'Region/State',
		'country_name' => 'Country',
		'zipcode_name' => 'Zipcode',
		'phone_name' => 'Phone',
		'confirm_regenerate' => 'Are you sure to regenerate the API Key?',
		'billing_details_update_sucess' => 'Billing details updated successfully',
		'phoneno_invalid' => 'Phone number format is invalid',
		'api_key_details'	=> 'Api Key Details',
		'api_key'		=>'Api Key',
		'api_key_message'			=> 'Clicking on regenerate  will generate a new key and you cannot use your old api key anymore.',
		'api_url_message'			=> 'In case of synchronisation issue, please provide the API URL as: ',
		'threshold_credit_title'  	=> 'Threshold Credit Notification',
		'threshold_credit'		  	=> 'Threshold Credit',
		'threshold_message'		  	=> 'Notification mail will be sent, when your credit balance reaches below this',
		'subscribe_newsletter'		=> 'Subscribed to mails',
		'timezone'					=> 'Timezone',
		'supplier_code'				=> 'Supplier Code',
		'address_details_title' 	=> 'Address Details',
		'address1' 					=> 'Address1',
		'address2' 					=> 'Address2',
		'address_details_update_sucess' => 'Address details updated successfully',
		'api_cdr_details'           => 'Api CDR Details',
		'cdr_reply_key'         	=> 'CDR Reply Key',
		'cdr_url'         			=> 'CDR URL',
		'cdr_enabled'         		=> 'Enable CDR',
		'cdr_details_update_sucess' => 'CDR details updated successfully',
		'api_cdr_url_message'       => 'http://example.com/reverseapi',
		'api_cdr_key_message'       => 'Any string',
		'cdr_details_head'         	=> 'What is CDR and How to use?',
		'cdr_details_info1'         => 'CDR stands for Content Delivery Reply. Once the order is completed or rejected we will post the result to the URL you supply for CDR URL in the above form.'.
										'Or alternatively you can provide the url when submitting the order also. The URL you provide with the order will be used if present. ',
		'cdr_details_info2'         => 'To authenticate that the result is sent by us, we will return the CDR Reply Key provided above along with the result.',
		'cdr_details_info3'         => 'Make sure to enable this in the above and start receiving the results of your order. This will save your bandwidth',
		'action_restricted_demo_site'=>'Action Restricted in Demo Site',
		'ip_range' => 'IP Range',
		'ip_range_note'				=> 'You can add IP Range in format ( 192.168.*.* ) or ( 192.168.1.* ).',
		'reset' => 'Reset',
		'ip_details_add_success' => 'IP Details Added Successfully',
		'ip_already_exists' => 'IP Already Exists',
		'alert_ip_message' => 'Are you sure want to reset all IP Addresses?',
		'allowed_ip' => 'Allowed Ips',
		'ip_message' => 'When empty, the IP from which the api is called first will be auto assigned'
	),
	'my-orders'	=> array(
		'title' => 'My Orders',
		'srch_order' => 'Search Order',
		'order_code' => 'Order Code',
		'model_name' => 'Model',
		'unlock_code' => 'Unlock Code',
		'imei_label' => 'IMEI',
		'unlock_tool' => 'Unlock Tool',
		'tool_name' => 'Tool',
		'service_name' => 'Service',
		'id' => 'Id',
		'date_added' => 'Date Added',
		'status_label' => 'Status',
		'no_records_found' => 'No records found',
	),
	'my-transaction-listing'	=> array(
		'title'				=> 'My Statement',
		'per_page'			=> 'Entry Per Page',
		'search'    		=> 'Search Transaction',
		'order_id'    		=> 'Order Id',
		'from_date'    		=> 'From Date',
		'to_date'    		=> 'To Date',
		'transaction_type'    		=> 'Transaction Type',
		'transaction_key'    		=> 'Transaction Key',
		'listing_id' => 'Id',
		'date_lbl' => 'Date',
		'description_lbl' => 'Description',
		'type_lbl' => 'Type',
		'amount_lbl' => 'Amount',
		'balance_lbl' => 'Balance',
		'current_balance' => 'Current Balance',
		'previous_balance' => 'Previous Balance',
		'amount_added' => 'Amount Added',
		'amount_reduced' => 'Amount Reduced',
		'imei_label' => 'IMEI',
		'service_label' => 'Service',
		'quantity_label' => 'Quantity',
		'user_name' => 'Username',
		'no_records_found' => 'No records found',
	),
	'view-order' => array(
		'view_title' => 'View Order',
		'update_title' => 'Update Order',
		'details_title' => 'Order Details',
		'order_code' => 'Order Code',
		'date_added' => 'Date Added',
		'tool_name' => 'Tool',
		'imei_label' => 'IMEI',
		'model_label' => 'Model',
		'phonemake_label' => 'Phone Make',
		'notes_label' => 'Notes',
		'credit_label' => 'Credit',
		'invalid_order' => 'Invalid Order',
		'call_type_label' => 'Call Type',
		'status'			=> 'Status',
		'unlock_code'		=> 'Unlock Code',
	),
	'email-activation'	=> array(
		'new_email_activation' => 'New email activation',
		'alternateEmail_newEmail_update_suc_msg' => 'Your email has been changed.',
		'alternateEmail_invalid_activation' => 'Invalid activation code.',
		'my_settings' => 'Settings',
	),
	//s//saravanan_273at14
		'loginhistory' 			=>array(
		'search_ip' 		=> 'Search By IP Address',
		'loginlog'  		=> 'Login History',
		'search'    		=> 'Search Login History',
		'browser'   		=> 'Browser Details',
		'per_page'			=> 'Page Size',
		'log_id'    		=> '#',
		'log_ip'    		=> 'IP',
		'log_date'  		=> 'DATE',
		'no_record_found' 	=> 'No records found to list',
		'from_date'			=> 'From Date',
		'to_date'			=> 'To Date'
	),
	'apijobs'				=> array(
		'invalid_api_key'	=> 'Invalid API Key',
		'invalid_api_method'	=> 'Invalid API Method',
		'not_enough_credit'	=> 'Insufficient Credit',
		'invalid_imei'	=> 'Invalid IMEI Number',
		'mail_sent_success'	=> 'Mail Sent Successfully',
		'no_data'			=> 'No result found to mail',
	),

	'apilog' 				=> array(
		'title'  			=> 'Api Log',
		'title_search'		=> 'Search Api Log',
		'imei' 				=> 'iDevice',
		'ip'  				=> 'IP',
		'amount'    		=> 'Amount',
		'date'   			=> 'Date',
		'status'			=> 'Status',
		'result'  			=> 'Result',
		'upload'			=> 'Upload',
		'no_record_found' 	=> 'No records found to list',
	),

	'unlock'				=> array(
		'title'				=> 'Unlock Tool',
		'tool_select'		=> 'Tool Select',
		'phonemake_id'		=> 'Device Make',
		'device_model'		=> 'Device Model',
		'imei'				=> 'IMEI Number',
		'notes' 			=> 'Additional Notes',

	),
	'memcached' => array(
		'memcached_down'=>'Cannot connect to memcache server please check and update settings',
		'base_message' 	=>  'Click to store cache',
		'files'			=> 'files',
		'memory'		=> 'memory and speed up the server',
		'Label'			=> 'Memcached settings <small>( store cache in memory will speed up your server )</small>',
	),
	'imei_order'					=>array(
		'title'						=> 'Unlocking Server',
		'imei'						=> 'IMEI',
		'bulk_imei'					=> 'Bulk IMEI',
		'imei_info'					=> 'Only 15 digit Number (dial *#06# for IMEI Number)',
		'bulk_imei_info'			=> 'You can enter several serial numbers (one per line) if you have several similar phones (for the same service and the same information).',
		'Imei_Add_to_bulk'			=> 'Add this IMEI to bulk entry',
		'tool'						=> 'IMEI Services',
		'credit'					=> 'Credit',
		'requires_network'				=> 'Network',
		'requires_network_info'			=> 'The brand of the mobile phone',
		'brand'							=> 'Brand',
		'brand_info'					=> 'The brand of the mobile phone',
		'model'							=> 'Model',
		'model_info'					=> 'The model of the mobile phone',
		'country'						=> 'Country',
		'country_info'					=> 'The country the network on which the mobile phone is currently locked belongs to',
		'network'						=> 'Network',
		'network_info'					=> 'The network on which the mobile phone is currently locked',
		'requires_model'				=> 'Brand',
		'requires_mep'					=> 'Mep',
		'requires_mep_info'	  			=> 'MEP number of the phone',
		'requires_model_info'			=> 'Mobile network on which the phone is currently locked',
		'requires_provider'				=> 'Country',
		'requires_provider_info'		=> 'The country the network on which the mobile phone is currently locked belongs to',
		'requires_pin'					=> 'PIN Number',
		'requires_pin_info'				=> 'Caution, this is not the SIM cards 4-digit PIN code',
		'requires_kbh'					=> 'KBH / KRH',
		'requires_kbh_info'				=> 'The S/N number of the phone',
		'requires_prd'					=> 'PRD',
		'requires_prd_info'				=> 'The PRD number of the phone',
		'requires_type'					=> 'Type',
		'requires_type_info'			=> 'Type *#0000# to find the type',
		'requires_reference'			=> 'Reference',
		'requires_reference_info'		=> 'The Reference number of the phone',
		'requires_locks'	  			=> 'Locks',
		'requires_udid'					=> 'UDID',
		'requires_udid_info'	  		=> '',
		'requires_serial'				=> 'SERIAL',
		'requires_serial_info'	  		=> '',
		'lock1'						=> 'Lock 1 (Network lock, MNC) NCK',
		'lock2'						=> 'Lock 2 (Network sub set) NSCK',
		'lock3'						=> 'Lock 3 (Service provider lock) SPK',
		'lock4'						=> 'Lock 4 (Cooperate lock) CCK',
		'lock5'						=> 'Lock 5 (Extended lock) ESL',
		'lock_info'					=> 'The type of codes you want to obtain',
		'notes'						=> 'Notes',
		'notes_info'				=> 'You can enter any additional notes or information you want including with your order here...',
		'comments'					=> 'Comments',
		'comments_info'				=> 'For yourself, useful to remember something about this order (name of your customer, ...)',
		'response_e_mail'			=> 'Response e-mail',
		'response_e_mail_info'		=> 'The email of your customer who will receive your custom reply (comma separated)',
		'service_email_notification'	=> 'Email Notification',
		'notification_e_mail_info'		=> 'Email notifiaction for this service',
		'refund_available_not_found'	=> 'Refund available if code is not found',
		'service_available_24'			=> 'Service Available 24/7',
		'unlock_guaranteed'				=> 'Unlock Guaranteed',
		'no_refund_for_bad_data'		=> 'No refund for bad requests',
		'invalid_access'				=> 'You are not Allowed !',
		'working_on_business'			=> 'Working on Business days only ',
		'order_place_terms'				=> 'Terms for ordering',
		'agree_notes'				=> 'I agree to the terms for ordering',
		'verification_available'	=> 'Verification available',
		),
	'file_order'					=>array(
		'title'						=> 'Unlocking Server',
		'tool'						=> 'File Services',
		'notes'						=> 'Notes',
		'file'						=> 'File',
		'bulk'						=> 'Multiple File',
		'bulk_info'					=> 'Zip all files and submit single file.',
		'notes_info'				=> 'You can enter any additional notes or information you want including with your order here...',
		'comments'					=> 'Comments',
		'comments_info'				=> 'For yourself, useful to remember something about this order (name of your customer, ...)',
		'response_e_mail'			=> 'Response e-mail',
		'response_e_mail_info'		=> 'The email of your customer who will receive your custom reply (comma separated)',
		'next_upload'				=> 'Next upload will start in',
	),
	'server_order'					=>array(
		'title'						=> 'Unlocking Server',
		'tool'						=> 'Server Services',
		'notes'						=> 'Notes',
		'username'					=> 'Username',
		'password'					=> 'Password',
		'serial'					=> 'Serial',
		'server'					=> 'Server',
		'order_type'				=> 'Order Type',
		'price_log'					=> 'Price / Log',
		'quantity'					=> 'Quantity',
		'user_name_info'			=> 'Valid Server Service Username',
		'server_user_name'			=> 'User Name',
		'notes_info'				=> 'You can enter any additional notes or information you want including with your order here...',
		'comments'					=> 'Comments',
		'comments_info'				=> 'For yourself, useful to remember something about this order (name of your customer, ...)',
		'response_e_mail'			=> 'Response e-mail',
		'response_e_mail_info'		=> 'The email of your customer who will receive your custom reply (comma separated)',
		'invalid_access'			=> 'You are not Allowed !',
		'specila_discoun_not'		=> 'Special Discount price is not included',
		'Qty_From'					=> 'Qty From',
		'Qty_From'					=> 'Qty To',
	),
	'imei_order_list'				=>array(
		'title'							=> 'IMEI Order History',
		'search'						=> 'Search Order',
		'service'						=> 'Service',
		'id'							=> 'ID',
		'imei'							=> 'IMEI',
		'bulkimei'						=> 'Bulk Imei',
		'completed_on'					=> 'Completed On',
		'order_code'					=> 'Order Code',
		'status'						=> 'Status',
		'api_order_status'				=> 'Order Status',
		'invalid_order' 				=> 'Invalid Order',
		'imei_order_details'			=> 'IMEI Order Details',
		'date_added'					=> 'Date Added',
		'unlock_code'					=> 'Unlock Code',
		'comments'						=> 'Comments',
		'code'							=> 'Code',
		'notes'							=> 'Notes',
		'verify'						=> 'Verify',
		'verify_order_details_title'	=> 'Verify Order details',
		'details'						=> 'Details',
		'attachment'					=> 'Attachment',
		'verification_sent_success'		=> 'Verifcation request sent successfully',
		'verified'						=> 'Verified',
		'in_process'					=> 'In Process',
		'verify_note_msg'				=> 'Having problems with unlock code, click here to verify.',
		'verify_question_msg'			=> 'Having problems with unlock code?',
		'verify_no_lbl'					=> 'No, it\'s working fine',
		'verification_in_process'		=> 'Under Verification',
		'date'							=> 'Date',
		'credits'						=> 'Credits',
		'reject_reason'					=> 'Reject Reason',
		'imei_reject_reason_title'		=> 'IMEI order Reject Reason',
		),
	'file_order_list'				=>array(
			'title'							=> 'File Order History',
			'search'						=> 'Search Order',
			'service'						=> 'Service',
			'id'							=> 'ID',
			'imei'							=> 'IMEI',
			'order_code'					=> 'Order Code',
			'status'						=> 'Status',
			'api_order_status'				=> 'Order Status',
			'invalid_order' 				=> 'Invalid Order',
			'file_order_details'			=> 'File Order Details',
			'date_added'					=> 'Date Added',
			'unlock_code'					=> 'Unlock Code',
			'comments'						=> 'Comments',
			'code'							=> 'Code',
			'notes'							=> 'Notes',
			'download_lbl'					=> 'Download',
			'estimated_start_in'			=> 'Estimated Start In',
			'percent_done'					=> 'Percent Done',
			'notes'							=> 'Notes',
			'verify'						=> 'Verify',
			'verify_order_details_title'	=> 'Verify Order details',
			'details'						=> 'Details',
			'attachment'					=> 'Attachment',
			'verification_sent_success'		=> 'Verifcation request sent successfully',
			'verified'						=> 'Verified',
			'in_process'					=> 'In Process',
			'verification_in_process'		=> 'Under Verification',
			'credits'						=> 'Credits',
			'reject_reason'					=> 'Reject Reason',
			'file_reject_reason_title'		=> 'File order Reject Reason',
		),
		'server_order_list'				=>array(
			'title'							=> 'Server Order History',
			'server_order_details'			=> 'Server Order Details',
			'search'						=> 'Search Order',
			'service'						=> 'Service',
			'note'							=> 'Note',
			'job_data'						=> 'Job Data',
			'result'						=> 'Result',
			'id'							=> 'ID',
			'credit'						=> 'Credit',
			'quantity'						=> 'Quantity',
			'server_user_name'				=> 'Username',
			'bulkimei'						=> 'Bulk Imei',
			'completed_on'					=> 'Completed On',
			'order_code'					=> 'Order Code',
			'result'						=> 'Result',
			'quantity'						=> 'Quantity',
			'job_data'						=> 'Job Data',
			'status'						=> 'Status',
			'api_order_status'				=> 'Order Status',
			'invalid_order' 				=> 'Invalid Order',
			'imei_order_details'			=> 'IMEI Order Details',
			'date_added'					=> 'Date Added',
			'unlock_code'					=> 'Unlock Code',
			'comments'						=> 'Comments',
			'code'							=> 'Code',
			'notes'							=> 'Notes',
			'verify'						=> 'Verify',
			'verify_order_details_title'	=> 'Verify Order details',
			'details'						=> 'Details',
			'attachment'					=> 'Attachment',
			'verification_sent_success'		=> 'Verifcation request sent successfully',
			'verified'						=> 'Verified',
			'in_process'					=> 'In Process',
			'verification_in_process'		=> 'Under Verification',
			'message'						=> 'Message',
			'verify_note_msg'				=> 'Having problems with unlock code, click here to verify.',
			'verify_question_msg'			=> 'Having problems with unlock code?',
			'verify_no_lbl'					=> 'No, it\'s working fine',
			'reject_reason'					=> 'Reject Reason',
			'server_reject_reason_title'	=> 'Server order Reject Reason',
		),
		'imei_order_send_message'		=> array(
		'title'							=> 'Send Mail',
		'message'						=> 'Message',
		'touser'						=> 'To User',
		'touser_and_response_email'		=> 'To user and Response Email\'s also',
		'cancel_order'					=> 'Are you sure you want to Cancel this Service Order? ',
		'reject_order'					=> 'Are you sure you want to Reject this Service Order? '
		),
		'file_order_send_message'		=> array(
		'title'							=> 'Send Mail',
		'message'						=> 'Message',
		'touser'						=> 'To User',
		'touser_and_response_email'		=> 'To user and Response Email\'s also',
		'cancel_order'					=> 'Are you sure you want to Cancel this Service Order? ',
		'reject_order'					=> 'Are you sure you want to Reject this Service Order? '
		),
		'service_list'					=> array(
		'title'							=> 'Service List',
		'unlocking_tool'				=> 'Unlocking Tool',
		'credit'						=> 'Credit',
		'delivery_time'					=> 'Delivery Time',
		'status'						=> 'Status',
		'mail_notification_title'		=> 'Mail Notification',
		'enable_mail_notification'		=> 'Mail Notification',
		'service_title'					=> 'Service',
		'mail_notification_success'		=> 'Mail Notification updated successfully',
		'mail_notification_info'		=> 'Do not want to receive notification by mail for orders placed in certain service? Turn off here.',
		'no_record_found'				=> 'No Record Found',

		),
	'my-transactions'		=> array(
		'no_records_found' => 'No records found to list',
		'search_txns' => 'Search Transactions',
		'txn_type' => 'Transaction Type',
		'txn_key' => 'Transaction Key',
		'invoice_id' => 'Invoice ID',
		'id' => 'ID',
		'date' => 'Date',
		'txn_type' => 'Transaction Type',
		'txn_amount' => 'Transaction Amount',
		'txn_notes' => 'Transaction Notes',
		'transaction_type_credit' => 'Credit',
		'transaction_type_debit' => 'Debit',
		'transaction_type_pending_credit' => 'Pending Credit',
		'transaction_type_pending_debit' => 'Pending Debit',
		'payment_id' => 'Payment ID',
		'running_balance' => 'Running Balance',
		'export_to_excel' => 'Export to Excel',
		'export_to_csv' => 'Export to CSV',
		'export_to_pdf' => 'Export to PDF',
		'view_order' => 'View Order',
	),
	'update-username'	=> array(
		'restricted_keyword' => 'Input has restricted keyword',
		'username_update_success'	=> 'Username updated Successfully',
	),

	'my-invoice-listing'	=> array(
		'title'				=> 'My Invoices',
		'per_page'			=> 'Entry Per Page',
		'search'    		=> 'Search Invoices',
		'no_records_found' 	=> 'No records found',
		'listing_id' 		=> 'Id',
		'due_date'    		=> 'Due Date',
		'paid_date'    		=> 'Paid Date',
		'total_lbl'    		=> 'Total',
		'status_lbl'    	=> 'Status',
		'paid_lbl'	    	=> 'Paid',
		'unpaid_lbl'    	=> 'Not Paid',
		'partially_paid_lbl'=> 'Partially Paid',
		'invoice_id'   		=> 'Invoice ID',
		'date_added'   		=> 'Date Added',
		'due_date'   		=> 'Due Date',
		'date_paid'   		=> 'Date Paid',
		'date_lbl' 			=> 'Date',
		'Total_Outstanding_Balance' 			=> 'Total Outstanding Balance',
	),
	'reseller-add-user'  =>array(
		'title'				=> 'Add User',
		'user_name'			=> 'Username',
		'email'				=> 'Email',
		'password'			=> 'Password',
		'api_credits'		=> 'Credit',
	),
	'reseller-user-list'	=> array(
		'title'				=> 'My User List',
		'user_name'			=> 'Username',
		'email'				=> 'Email',
		'status'			=> 'Status',
		'credit'			=> 'Credit',
		'no_records_found'	=> 'No Records Found',
		),
	'process-payment' 		=> array(
		'title'				=> 'Payment',
		'payment_success_msg' => 'Thank you for making your payment. Please wait while your payment is processed. You will be notified once it\'s completed. <a href="VAR_INVOICE_LINK">Click here</a> to view your invoices and check the payment status. ',
		'payment_error_msg' => 'Sorry your payment has been cancelled. <a href="VAR_INVOICE_LINK">Click here</a> to view your invoices and check the payment status',
	),
	'edit-reseller-user-list'	=> array(
		'title'				=> 'Edit Resellers User',
		'first_name'		=> 'First name',
		'last_name'			=> 'Last name',
		'user_id'			=> 'User Id',
		'user_code'			=> 'User Code',
		'phone'				=> 'Phone',
		'member_since'		=> 'Member Since',
		'about_me'			=> 'About Me',
		'phone'				=> 'Phone',
		'phone'				=> 'Phone',
		'credit'			=> 'Credit',

		),
	'reseller-credit-rebate'	=> array(
		'title'				=> 'Edit Resellers User',
		'user_name'			=> 'Username',
		'credit'			=> 'Credit',
		'add_credit'		=> 'Add Credit +',
		'rebate_credit'		=> 'Rebate Credit -',
		'note'				=> 'Note',
		'paid'				=> 'Paid',
		'success_message'	=> 'Credit Update Successfully',
		),
	'reseller-set-pricing-imei'	=> array(
		'title'				=> 'Edit Resellers User',
		'your_price'		=> 'Your Price',
		'default_price'		=> 'Default Price',
		'new_price'			=> 'New Price',
		'store_price'		=> 'Store Price',
		'success_message'	=> 'Pricing Updated Successfully',

		),
	'reseller-user-imei-order-list'	=> array(
		'title'				=> 'My User List Orders',
		'id'				=> '#ID',
		'service'			=> 'Servcie',
		'imei'				=> 'IMEI',
		'status'			=> 'Status',
		'replay'			=> 'Replay',
		),
	'reseller-site-settings'	=> array(
		'title'					=> 'Reseller Site Settings',
		'site_name'				=> 'Site Name',
		'site_url'				=> 'Site Url',
		'site_logo'				=> 'Logo Url',
		'email_from_name'		=> 'Email From Name',
		'support_email'			=> 'Support Email',
		),
	'reseller-statement'	=> array(
		'title'					=> 'Reseller User Statement',
		),
	'reseller-mailer-settings'	=> array(
		'title'					=> 'Reseller Mailer Settings',
		'driver'				=> 'Mail Driver',
		'driver_help'			=> 'Supports both SMTP and Mail, default SMTP ',
		'host'					=> 'Host',
		'host_help'				=> 'provide the host address of the SMTP server',
		'port'					=> 'Port',
		'port_help'			    => 'SMTP port',
		'encryption'			=> 'Encryption',
		'encryption_help'		=> 'encryption protocol that should be used, common values are ssl, tls or leave as empty',
		'from_address'			=> 'From Address',
		'from_address_help'		=> 'Email address from which the mails are to be sent',
		'from_name'				=> 'From Name',
		'from_name_help'		=> 'Name of the sender for sending mails',
		'username'				=> 'Username',
		'username_help'			=> ' Provide the username of your SMTP server required for authentication',
		'password'				=> 'Password',
		'password_help'			=> ' password required by your SMTP server to send out messages',
		'mailer_update_success'	=> 'Mailer Settings Updated successfully',
		'file_not_writable'		=> 'Your mail config file is not writable. Contact admin to set file writable for webserver. File location : app/config/mail.php !!',
		'test_mail_to'          => "Send to e-mail",
		'mail_subject'          => "Mail Subject",
		'mail_content'          => "Mail Content",
		'smtp_details'          => "SMTP Details",
		'send_test_mail'        => "Send Test Mail",
		'page_info'             => "Make sure to try settings in Outlook or in Thunderbird to see all is working before setting the smtp settings here. If the settings are not correct, users will not receive mails",
	),

	'login-security'	=> array(
		'title'					=> 'Login Security',
		'ip_range'					=> 'IP Range',
		'access_block_remove_success'					=> 'IP/Country Removed Successfully',
		'ip_range_note'				=> 'You can add IP Range in format ( 192.168.*.* ) or ( 192.168.1.* ).',
		'2step_verification' => '2-Step Verification',
		'secret_code'	=>	'Secret Code',
		'uri' => 'Key URI:',
		'enable'	=>	'Enable',
		'disable'	=>	'Disable',
		'test_your_code'	=>	'Test Your Code',
		'test_code' => 'Test Code',
		'login_security'	=>	'Back to Login Security',
		'disabled_message' => '2-step verification has been disabled successfully',
		'trust_this_computer' => 'Trust this Computer',
		'remove_trust' => 'Remove this computer from my trusted list.',
		'untrusted_message' => 'This computer is removed from trusted list.',
		'trusted_message' => 'This computer is added to trusted list.',
		'secret_code_scan' => 'Secret Code to Scan',
		'proceed' => 'Proceed',
		'activate_2step' => 'Activate 2Step Verification',
		'activated_2step_verification' => '2-step verification has been activated successfully'
	 ),

		'menu_manager'				=> array(
		'title'							=> 'Menu Manager',
		'name'							=> 'Name',
		'uid'							=> 'Users',
		'groupid'						=> 'Listed In',
		'link'							=> 'Link',
		'display'       				=> 'Display',
		'req_login'       				=> 'Login Required',
		'external'       				=> 'Link as a external',
		'newwindow'       				=> 'Open in new Window',
		'afterloginshow'       			=> 'Dont show if logged in',
		 ),
		'custom_page'					=> array(
		'title'							=> 'Title',
		'meta_tag_keyword'				=> 'Meta tag Keywords',
		'name'							=> 'Name',
		'display'       				=> 'Display',
		'req_login'       				=> 'Login Required',
		'date_added'       				=> 'Date',
		),
		'banner_settings'				=> array(
		'title'							=> 'Title',
		'content'						=> 'Description',
		'image_name'					=> 'Image',
		'display'						=> 'Display',
		'id'							=> '#ID',
		'published'						=> 'Published',
		),
		'customer_review'				=> array(
		'title'							=> 'Voice your opinion! Review Now',
		'review_header'					=> 'Your opinion in one sentence',
		'review'						=> 'Your full review',
		'name'							=> 'Name',
		'email'							=> 'Email',
		),

		'ticket_system'					=> array(
		'title'							=> 'Support Ticket - Please Select Department',
		'title1'						=> 'Support Ticket',
		'you_are_not_allowed'			=> 'You are not Allowed !',
		'id'							=> '#ID',
		'date'							=> 'Date',
		'name'							=> 'Name',
		'email'							=> 'E-mail',
		'service'						=> 'Service',
		'order_code'					=> 'Order Code',
		'subject'						=> 'Subject',
		'priority'						=> 'Priority',
		'message'						=> 'Message',
		'status'						=> 'Status',
		'reply'							=> 'Reply',
		),
		'download'						=> array(
		'title'							=> 'Download File',
		'directory'						=> 'Directory',
		'item'							=> 'Item',
		'file_name'						=> 'File Name',
		'action'						=> 'Action',
		'file_size'						=> 'File Size',
		'downloaded'					=> 'Downloaded',
		),
		'add_fund'						=> array(
		'Payment_Gateway'  => 'Payment Gateway',
		'Fees'  => 'Fees',
		'Total_Amount'  => 'Total Amount',
		'Amount_to_add'  => 'Amount to add',
		),
		 'email_performance' =>array(
		 'IMEI_place_order_confirmation'	=> 'IMEI place order confirmation',
		 'IMEI_order_completed' 			=> 'IMEI order completed',
		 'IMEI_order_rejected' 				=> 'IMEI order rejected',
		 'File_place_order_confirmation'	=> 'File place order confirmation',
		 'File_order_completed' 			=> 'File order completed',
		 'File_order_rejected' 				=> 'File order rejected',
		 'Server_place_order_confirmation' 	=> 'Server place order confirmation',
		 'Server_order_completed' 			=> 'Server order completed',
		 'Server_order_rejected' 			=> 'Server order rejected',
		 'title' 							=> 'Email Performance',
		 ),
	'paypal-payment'	=> array(
		'title'			=> 'Paypal Payment',
		'transaction_id_label'			=> 'Transaction Id',
		'receiver_email'			=> 'Receiver Email',
		'payment_notes'			=> 'Payment Notes',
		'payment_notes_holder'			=> 'Payment Notes',
		'submit'			=> 'Submit',
		'preview_label'		 => 'Transaction Details',
		'invalid_transaction_id'	=> 'Invalid Transaction Id',
		'invalid_receiver_email'	=> 'Sorry could not process the transactions. Admin has been notified on this payment. Please try later.',
		'api_details_unset'	=> 'Sorry could not process the transaction. Admin has been notified on this payment. Please try later.',
		'api_details_submit_success' => 'Payment details submitted successfully',
		'transaction_already_exist' => 'Payment record already exist. Please <a href="VAR_TRANSACTION_LINK">Click here</a> to view the payment.',
		'invalid_amount' => 'Invalid amount. Amount received is VAR_AMOUNT ',
		'invalid_status' => 'Payment status is not completed.',
		'invalid_currency' => 'Payment currency is not in your account currency.',
		'invalid_receiver' => 'Payment has not been made to valid receiver',

	),

	'submit-payment' => array(
		'submit_notes'       => 'Provide the details of the payment made. Once the payment is received, the admin will update the payment status and transactions will be made in your account accordingly.',
		'company'			=> 'Company',
		'payment_notes'      => 'Payment notes',
		'payment_notes_holder'    => 'Provide details on the receiver and payment for. Limit to '.Config::get('site.payment_notes_max_length'). ' characters.',
		'first_name'   		 => 'Sender\'s First name',
		'last_name'   		 => 'Sender\'s Last name',
		'email'   		 	 => 'Email / Sonork',
		'city'   		 	 => 'City',
		'state'   		 	 => 'State',
		'country'   		 => 'Country',
		'mtcn_number'        => 'Transaction number' ,
		'sender_details_title'   => 'Sender Details',
		'receiver_details'   			 => 'Receiver Details',
		'preview_label'		 => 'Payment Details',
		'receiver_label'	 => 'Receiver',
		'notes_label'	 => 'Payment Notes',
	)

);